### ISSUE TITLE
silently fails when pandoc is not installed

### ISSUE THREAD

**Issue by milahu** [willjp/mediawiki-dump2html#3]

**Comment by willjp** [comment]
Thanks so much for this @milahu , I never expected anyone else would use this.

**Comment by milahu** [comment]
> I never expected anyone else would use this.

to be honest, i dont use it ^^

the problem is that pandoc cannot render mediawiki templates,
and the problem of mediawiki is that XML-import is slow.

so ideally, i want a hybrid solution, which is pretty and fast.
pretty as in: produce a git repo with github-flavored-markdown with rendered templates.
it can be faster than XML-import, by skipping the creation of SQL tables/indices.

possible solutions:
https://github.com/peterjc/mediawiki_to_git_md - using pandoc for rendering, no support for mediawiki templates

**Comment by willjp** [comment]
> to be honest, i dont use it ^^

Haha, that's fair -- This whole repos was kind of an excuse to try throwing golang at a problem :).
It's nice to have a copy of my notes when I'm rebuilding my servers though :sweat_smile: 

> so ideally, i want a hybrid solution, which is pretty and fast.

So I'm full of optimism/bad-ideas, 
but I wonder how hard it would be to read the rendered pages one character at a time to parse the template logic.
I think the templates themselves are included in the mediawiki dump. It might not be all that bad.
The documentation make them look not too complex, at least from the outside: https://www.mediawiki.org/wiki/Help:Templates
